import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "CHOI PORTFOLIO",
  description: "Generated by Choi",
};

export default function SubLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return <div className="sub-wrapper">{children}</div>;
}
