import type { Metadata } from "next";
import "@/scss/index.scss";
import NavMenu from "./_components/NavMenu";
import TopFixMenu from "./_components/TopFixMenu";

export const metadata: Metadata = {
  title: "CHOI PORTFOLIO",
  description: "Generated by Choi",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="kr">
      <body>
        <TopFixMenu />

        <NavMenu />
        {children}
      </body>
    </html>
  );
}
